---
title: "KC resume"
author: Kseniia Sergeeva
output:
  pagedown::html_resume:
    self_contained: false
    css: custom_resume.css
knit: pagedown::chrome_print
---


Aside
====================================

Contact info
------------------------------------

::: concise
<i class="fa fa-envelope"></i> k_s_egorova@mail.ru <br>
<i class="fas fa-phone"></i> +7 (909) 946-64-09 <br>
<i class="fas fa-home"></i> [kc-design.netlify.app/](https://kc-design.netlify.app/)<br>

For more information, please contact me via email
:::


Знание программ
------------------------------------

<i class="fas fa-folder-open"></i> Microsoft Office <br>
<i class="fas fa-laptop"></i> AutoCAD <br>
<i class="fas fa-camera"></i> Photoshop <br>
<i class="fas fa-cube"></i> SketchUp <br>
<i class="fas fa-folder-open"></i> Enscape <br>

Повышение квалификации
------------------------------------

<i class="fas fa-certificate"></i> **Курс SketchUp для ландшафтного дизайна**<br>
50 ак. часов в классе и 40 ак. часов домашней работы, 2019 

<i class="fas fa-certificate"></i> **Wall Street Institute языковые курсы**<br>
Wall Street Institute, 2013

Дополнительные сведения
------------------------------------

<i class="fas fa-volume-up"></i> **языки:** Русский (Родной), Английский (Intermediate)

<i class="fas fa-car"></i> **легковые авто:**Водительские права (B — легковые авто), Наличие личного автомобиля


Main
====================================

Сергеева Ксения Владимировна {#title}
------------------------------------

Умею работать в режиме со сжатыми сроками и большим количеством задач. Стремлюсь к постоянному самосовершенствованию и уделяю особое внимание деталям, открыта для всего нового.

Высшее образование {data-icon=graduation-cap}
------------------------------------

### Российский государственный аграрный университет

Инженер по специальности « Садово-парковое и ландшафтное строительство»

Москва

2016 - 2014



### Российский государственный аграрный университет

Магистр по направлению Ландшафтная архитектура

Москва

2012 - 2007




Опыт работы {data-icon=laptop}
------------------------------------

### Главный ландшафтный дизайнер

Мастерская ландшафтного дизайна </br>
Александры Тимофеевой [Architect.boutique](https://architect.boutique/)

Москва

Июль 2021 - Июнь 2020


### Ландшафтный дизайнер, 3D визуализатор

фрилансер

Москва

Июнь 2020 - Декабрь 2019

::: concise
Разработка проектных чертежей, визуализация проектов
:::

### Менеджер по закупкам

ООО "Контур-97"

Москва

Июнь 2020 - Январь 2015

::: concise
работа с почтой, иностанные переводы, консцльтация иностранных клиентов
:::


### Помощник ландшафтного архитектора 

Сэликс Дизайн 

Москва

Ноябрь 2015 - Апрель 2012

::: concise
Разработка проектных чертежей, визуализация проекта. 
Выезд на объекты, уход за садом, ведение деловой переписки 
:::

### Практикант

"Губернские Усадьбы" 

Москва

Август 2010 - Май 2010

::: concise
Прохождение производственной практики.
Разработка проектных чертежей, визуализация проектов
Выезд на объекты, уход за садом
:::

Достижения  
------------------------------------

### 1 место в номинации "Большой сад 2020"

1 место в номинации "Большой сад 2020" Воронежского международного фестиваля "Город-сад", за проект «Red Garden»

N/A 

2020

### Лауреат премии Правительства Москвы 2012 года 

лучший проект комплексного благоустройства природных и озелененных территорий города Москвы, за проект «Реконструкция прибрежной территории Измайловского острова. Москва»

N/A

2012